### ISSUE TITLE
Double reander

### ISSUE THREAD

**Issue by monkeymq** [bukalapak/snowboard#80]
Hi, I got a strange problem when using Snowboard, as shown in the figure,
Snoarboard rendered the same API multiple times
![image](https://user-images.githubusercontent.com/29622442/65744975-c0256e80-e12c-11e9-8740-4e41270bb1cc.png)

I used fury-cli to convert swagger json to APIB. Could you help me out? Thanks

**Comment by katylava** [comment]
Same here. I took the `## Group ...` headers out and it renders fine, but then I can't group anything.

**Comment by katylava** [comment]
And I don't know if this is related but there is no way to see the description for the Group.

**Comment by Kontinuation** [comment]
Same problem here, I used the binary release snowboard-v3.6.0.linux-amd64.tar.gz.
Maybe I should switch to a more stable API Blueprint renderer.

**Comment by subosito** [comment]
@Kontinuation @katylava Please try v3.7.0 and let me know the result. Hopefully this issue is fixed in v3 before we release Snowboard v4 soon.

**Comment by Kontinuation** [comment]
I tried v3.7.0 linux binary release, still the same problem.

**Comment by Kontinuation** [comment]
I tried the master branch and it does not have this problem, do we need to fix this on v3 branch?
